/** @typedef {{ id: string; title: string; description: string; cards: { front: string; back: string }[] }} Deck */

function deck(id, title, description, rows) {
  return {
    id,
    title,
    description,
    cards: rows.map(([front, back]) => ({ front, back })),
  };
}

/** Expanded Linux+ (XK0-005-style) flashcard library — replaces JSON deck list at runtime. */
export const LINUX_PLUS_FLASHCARD_DECKS = [
  deck("lp-cmd-core", "Commands — core CLI", "Navigation, text, and process essentials.", [
    ["Print working directory", "pwd"],
    ["List all files including hidden (-a), long (-l)", "ls -la"],
    ["Copy recursively with permissions", "cp -a src dest"],
    ["Move or rename a file", "mv old new"],
    ["Remove empty directory", "rmdir dirname"],
    ["Remove recursively (careful)", "rm -r path"],
    ["Create nested directories", "mkdir -p a/b/c"],
    ["Show first lines of a file", "head -n 20 file"],
    ["Show last lines and follow (-f)", "tail -f /var/log/syslog"],
    ["Page through a file", "less file"],
    ["Count lines/words in a file", "wc -l file"],
    ["Sort lines uniquely", "sort -u file"],
    ["Remove duplicate adjacent lines", "uniq"],
    ["Translate or squeeze characters", "tr 'A-Z' 'a-z'"],
    ["Cut columns from text", "cut -d: -f1 /etc/passwd"],
    ["Stream editor: replace on line", "sed -i 's/old/new/g' file"],
    ["Default shell for current user", "echo $SHELL"],
    ["Re-run last command with sudo", "sudo !!"],
    ["Repeat previous command", "!!"],
    ["History line n", "!n"],
    ["Clear terminal screen", "clear or Ctrl+L"],
    ["Send SIGTERM to PID", "kill PID"],
    ["Send SIGKILL (last resort)", "kill -9 PID"],
    ["Show command type (alias, file, builtin)", "type cmd"],
    ["Brief manual section", "man -k keyword"],
  ]),
  deck("lp-files-fhs", "Filesystem & FHS", "Paths, mounts, and hierarchy.", [
    ["Essential binaries (single-user)", "/bin"],
    ["System binaries (admin)", "/sbin"],
    ["Shared libraries", "/lib or /lib64"],
    ["Variable data (logs, spool)", "/var"],
    ["Host-specific config", "/etc"],
    ["Optional add-on packages", "/opt"],
    ["Removable media mount point", "/media or /mnt"],
    ["Per-user data (home)", "/home"],
    ["Boot loader & kernel files", "/boot"],
    ["Device nodes", "/dev"],
    ["Kernel & process pseudo-fs", "/proc"],
    ["Volatile runtime data (PID files, sockets)", "/run"],
    ["Kernel tunables (sysctl)", "/sys"],
    ["Temporary files (often cleared on boot)", "/tmp"],
    ["Default web root (typical)", "/var/www/html"],
    ["Cron spool for users", "/var/spool/cron/crontabs"],
    ["Default Apache vhost config dir (Debian)", "/etc/apache2/sites-available"],
    ["SSH server daemon config", "/etc/ssh/sshd_config"],
    ["Resolver config (DNS)", "/etc/resolv.conf"],
    ["Name service switch order", "/etc/nsswitch.conf"],
    ["Static hostname → IP map", "/etc/hosts"],
    ["System hostname (systemd)", "/etc/hostname"],
    ["Sudo policy fragments", "/etc/sudoers.d/"],
    ["Login definitions (UID ranges, password aging)", "/etc/login.defs"],
  ]),
  deck("lp-perms", "Permissions & ACLs", "chmod, special bits, ACLs.", [
    ["Symbolic: add exec for owner", "chmod u+x file"],
    ["Symbolic: remove write for others", "chmod o-w file"],
    ["Numeric: rwxr-x---", "chmod 750 file"],
    ["Set UID on executable", "chmod u+s binary"],
    ["Set GID on directory (inherit group)", "chmod g+s /shared"],
    ["Sticky bit on world-writable dir", "chmod +t /tmp"],
    ["Change owner and group", "chown user:group file"],
    ["Recursive chown", "chown -R user:group dir"],
    ["Change primary group of file", "chgrp group file"],
    ["Default file mode mask", "umask (e.g. 022)"],
    ["List ACLs on file", "getfacl file"],
    ["Set ACL read for user bob", "setfacl -m u:bob:r file"],
    ["Remove all ACLs from file", "setfacl -b file"],
    ["Default ACL on directory (inherit)", "setfacl -d -m u:bob:rx dir"],
    ["View file mode as octal", "stat -c '%a' file"],
    ["Find setuid binaries", "find / -perm -4000 2>/dev/null"],
    ["SGID on dir: new files inherit", "group from parent directory"],
    ["World-writable dirs risk", "trojan/worm replacement of binaries"],
    ["umask 027 effect", "files 640 dirs 750 typical"],
    ["chmod reference file", "chmod --reference=rfile target"],
    ["ACL mask entry", "caps effective permissions for ACL users"],
    ["Immutable attribute (ext)", "chattr +i file (lsattr)"],
    ["ls numeric IDs (no name resolve)", "ls -n"],
  ]),
  deck("lp-users", "Users, groups & auth", "Accounts, PAM, sudo.", [
    ["User account database", "/etc/passwd"],
    ["Password hashes (shadowed)", "/etc/shadow"],
    ["Group definitions", "/etc/group"],
    ["Create user with home", "useradd -m username"],
    ["Set user password", "passwd username"],
    ["Modify user shell/home", "usermod -s /bin/bash user"],
    ["Delete user and home", "userdel -r user"],
    ["Add user to supplementary groups", "usermod -aG group user"],
    ["Switch user (login shell)", "su - username"],
    ["Edit sudoers safely", "visudo"],
    ["List user groups", "groups user"],
    ["Change effective group", "newgrp groupname"],
    ["Last successful logins", "last"],
    ["Failed login attempts", "faillock --user user (or pam_tally2 legacy)"],
    ["PAM config directory", "/etc/pam.d/"],
    ["Lock password (shadow)", "passwd -l user"],
    ["Force password change next login", "chage -d 0 user"],
    ["Display user/group IDs", "id username"],
    ["who is logged in", "who or w"],
    ["SSH public key for auth on server", "~/.ssh/authorized_keys"],
    ["Known hosts (client)", "~/.ssh/known_hosts"],
    ["Default nologin shell path", "/sbin/nologin"],
    ["List failed ssh (journal)", "journalctl -u ssh"],
  ]),
  deck("lp-systemd", "systemd & services", "Units, targets, journals.", [
    ["Start service now", "systemctl start nginx"],
    ["Stop service", "systemctl stop nginx"],
    ["Enable at boot", "systemctl enable nginx"],
    ["Disable at boot", "systemctl disable nginx"],
    ["Reload unit files after edit", "systemctl daemon-reload"],
    ["Show service status", "systemctl status nginx"],
    ["List active units type service", "systemctl list-units --type=service --state=running"],
    ["Edit unit override", "systemctl edit unit"],
    ["Default target (like runlevel)", "systemctl get-default"],
    ["Set default to multi-user", "systemctl set-default multi-user.target"],
    ["Boot logs (kernel ring)", "journalctl -k"],
    ["Follow unit logs", "journalctl -u nginx -f"],
    ["Since today", "journalctl --since today"],
    ["Persist journal size config", "/etc/systemd/journald.conf"],
    ["Timer unit lists", "systemctl list-timers"],
    ["Socket activation", ".socket unit activates .service"],
    ["Mask unit (prevent start)", "systemctl mask unit"],
    ["Unmask", "systemctl unmask unit"],
    ["Show unit file path", "systemctl show -p FragmentPath nginx"],
    ["Isolate target (switch)", "systemctl isolate rescue.target"],
    ["Reload service config", "systemctl reload nginx"],
    ["Check for failed units", "systemctl --failed"],
  ]),
  deck("lp-net", "Networking", "IP, DNS, sockets, firewall.", [
    ["Show IP addresses", "ip addr show"],
    ["Add IP to interface", "ip addr add 10.0.0.5/24 dev eth0"],
    ["Bring interface up", "ip link set eth0 up"],
    ["Show routing table", "ip route show"],
    ["Add default gateway", "ip route add default via 192.168.1.1"],
    ["Test DNS resolution", "dig +short example.com"],
    ["Query specific record MX", "dig MX example.com @8.8.8.8"],
    ["Listening TCP/UDP numeric", "ss -tuln"],
    ["Process bound to port", "ss -tlnp"],
    ["Legacy interface config (RHEL)", "/etc/sysconfig/network-scripts/"],
    ["Netplan (Ubuntu YAML)", "/etc/netplan/*.yaml"],
    ["Hostnamectl set hostname", "hostnamectl set-hostname host"],
    ["Test reachability (no ICMP in some sandboxes)", "curl -I https://host"],
    ["View ARP cache", "ip neigh show"],
    ["Track route to host", "traceroute host"],
    ["NetworkManager TUI", "nmtui"],
    ["firewalld rich rule zone", "firewall-cmd --zone=public ..."],
    ["iptables list nat", "iptables -t nat -L -n -v"],
    ["nft list ruleset", "nft list ruleset"],
    ["Loopback always up", "lo 127.0.0.1"],
    ["Bonding / teaming", "multiple NICs one logical link"],
    ["VLAN subinterface", "eth0.100 on eth0"],
    ["TCP wrapper files (legacy)", "/etc/hosts.allow /etc/hosts.deny"],
    ["nmcli con show", "NetworkManager connections"],
  ]),
  deck("lp-pkg", "Packages", "dpkg/apt/rpm/yum/dnf/zypper.", [
    ["Debian: update index", "apt update"],
    ["Debian: install package", "apt install pkg"],
    ["Debian: remove keep config", "apt remove pkg"],
    ["Debian: purge remove config", "apt purge pkg"],
    ["Debian: search package", "apt search keyword"],
    ["Low-level Debian install deb", "dpkg -i package.deb"],
    ["Fix broken deps", "apt --fix-broken install"],
    ["RPM: install", "rpm -ivh pkg.rpm"],
    ["YUM/DNF: install", "dnf install pkg (or yum)"],
    ["List installed RPM", "rpm -qa | grep pkg"],
    ["Which package owns file", "rpm -qf /path/file"],
    ["SUSE ZYpp CLI", "zypper in pkg"],
    ["Show repo list DNF", "dnf repolist"],
    ["Hold package version apt", "apt-mark hold pkg"],
    ["Show package files", "dpkg -L pkg"],
    ["Download only (no install) apt", "apt download pkg"],
    ["Build from source typical steps", "./configure && make && sudo make install"],
    ["Flatpak search", "flatpak search app"],
    ["Snap list", "snap list"],
    ["Kernel headers package pattern", "kernel-devel (RHEL) linux-headers-$(uname -r) (Debian)"],
  ]),
  deck("lp-disk", "Storage & filesystems", "mount, LVM, fstab.", [
    ["Block devices tree", "lsblk"],
    ["Filesystem types on devices", "lsblk -f"],
    ["Mount by UUID from fstab", "mount UUID=..."],
    ["Unmount busy filesystem", "umount -l lazy or fuser -vm"],
    ["/etc/fstab fields order", "device mountpoint fstype options dump pass"],
    ["pass column in fstab (fsck order)", "0 skip, 1 root, 2+ others"],
    ["Create ext4 on partition", "mkfs.ext4 /dev/sdb1"],
    ["Label ext filesystem", "e2label /dev/sdb1 MYDATA"],
    ["Check ext filesystem", "fsck /dev/sdb1 (unmounted)"],
    ["LVM: physical volume create", "pvcreate /dev/sdb1"],
    ["LVM: volume group create", "vgcreate vg0 /dev/sdb1"],
    ["LVM: logical volume", "lvcreate -L 10G -n lv0 vg0"],
    ["LVM: extend LV + FS", "lvextend -r -l +100%FREE /dev/vg0/lv0"],
    ["Swap file quick steps", "fallocate, mkswap, swapon"],
    ["See swap usage", "swapon --show"],
    ["Inode exhaustion symptom", "disk full but df shows space — cannot create file"],
    ["du one level summary", "du -h --max-depth=1"],
    ["find large files", "find / -xdev -size +100M"],
    ["tune2fs list ext params", "tune2fs -l /dev/sda1"],
    ["mount bind read-only", "mount --bind -o ro old new"],
    ["systemd automount", ".automount unit"],
    ["SMR/SSD trim (fstrim)", "fstrim -av"],
  ]),
  deck("lp-sec", "Security hardening", "SSH, firewalls, crypto basics.", [
    ["Disable root SSH login", "PermitRootLogin no in sshd_config"],
    ["SSH key-based auth", "PubkeyAuthentication yes"],
    ["List open files by process", "lsof -p PID"],
    ["Generate SSH key ed25519", "ssh-keygen -t ed25519"],
    ["Copy local pubkey to remote", "ssh-copy-id user@host"],
    ["Verify file integrity", "sha256sum file"],
    ["GPG symmetric encrypt file", "gpg -c file"],
    ["List listening ports root", "ss -tulnp"],
    ["SELinux enforcing check", "getenforce"],
    ["SELinux context on file", "ls -Z file"],
    ["Restore default SELinux context", "restorecon -Rv path"],
    ["AppArmor status", "aa-status"],
    ["umask for secure files", "027 or 077 stricter"],
    ["Fail2ban purpose", "ban IPs after auth failures"],
    ["TCP wrappers (legacy)", "hosts.allow / hosts.deny"],
    ["auditd log path typical", "/var/log/audit/audit.log"],
    ["Search audit log ausearch", "ausearch -m avc -ts recent"],
    ["cryptsetup LUKS open", "cryptsetup luksOpen dev mapper"],
    ["chmod dangerous world-writable", "find / -perm -002 -type d"],
    ["disable unused services", "systemctl disable --now unit"],
    ["Kernel module signing (concept)", "integrity of loaded modules"],
    ["chroot vs container (concept)", "chroot only FS isolation; namespaces broader"],
  ]),
  deck("lp-script", "Shell scripting", "bash, tests, loops.", [
    ["Shebang portable bash", "#!/usr/bin/env bash"],
    ["Exit on error", "set -e"],
    ["Exit on undefined var", "set -u"],
    ["Pipefail", "set -o pipefail"],
    ["Function definition", "myfn() { ... }"],
    ["Test integer compare", "if [ \"$a\" -eq 1 ]; then"],
    ["Test string equals", "if [ \"$a\" = \"x\" ]; then"],
    ["File exists test", "[ -f path ]"],
    ["Directory exists", "[ -d path ]"],
    ["For loop over lines", "while IFS= read -r line; do ...; done < file"],
    ["Arithmetic in bash", "(( x = y + 1 ))"],
    ["Default parameter value", "${var:-default}"],
    ["Script argument count", "$#"],
    ["All args as single string", "$*"],
    ["Source another script", "source file.sh or . file.sh"],
    ["Capture command output", "out=$(cmd)"],
    ["Case statement pattern", "case $x in a|b) ;; esac"],
    ["Debug trace execution", "bash -x script.sh"],
    ["sleep seconds", "sleep 5"],
    ["cron single user entry", "crontab -e"],
    ["at job once", "at now + 5 minutes"],
  ]),
  deck("lp-containers", "Containers & virtualization", "Docker/Podman basics.", [
    ["List running containers", "docker ps"],
    ["List all containers", "docker ps -a"],
    ["Run interactive tty", "docker run -it ubuntu bash"],
    ["Build image from Dockerfile", "docker build -t myimg ."],
    ["Push image to registry", "docker push repo:tag"],
    ["Exec shell in running container", "docker exec -it name bash"],
    ["Container logs follow", "docker logs -f name"],
    ["Remove stopped container", "docker rm name"],
    ["Remove image", "docker rmi id"],
    ["Network driver default single host", "bridge"],
    ["Volume mount host to container", "-v /host:/container"],
    ["Podman rootless", "runs without daemon as user"],
    ["docker compose up", "multi-container stack"],
    ["Inspect container metadata", "docker inspect name"],
    ["Prune unused objects", "docker system prune"],
  ]),
  deck("lp-trouble", "Troubleshooting & logs", "boot, disk, performance.", [
    ["Boot journal from prior boot", "journalctl -b -1"],
    ["Kernel ring buffer now", "dmesg | tail"],
    ["Check disk SMART brief", "smartctl -H /dev/sda"],
    ["Inode usage per FS", "df -i"],
    ["Load average meaning", "1/5/15 min runnable + uninterruptible average"],
    ["CPU per process live", "top then P sort"],
    ["Memory pressure", "free -h and vmstat 1"],
    ["Disk latency iostat", "iostat -xz 1"],
    ["strace attach PID", "strace -p PID"],
    ["tcpdump on interface", "tcpdump -i eth0 port 80"],
    ["rescue shell systemd", "systemd.debug-shell=1 or rd.break"],
    ["fsck forced next boot", "tune2fs -c max_mount_counts or touch /forcefsck"],
    ["Missing library ldd", "ldd binary shows not found"],
    ["core dump enable ulimit", "ulimit -c unlimited"],
    ["sar historical CPU", "sar -u"],
  ]),
  deck("lp-kernel", "Kernel & modules", "modprobe, sysctl.", [
    ["List loaded modules", "lsmod"],
    ["Module info", "modinfo module_name"],
    ["Load module + deps", "modprobe module"],
    ["Remove module", "modprobe -r module"],
    ["Blacklist module", "file in /etc/modprobe.d/*.conf"],
    ["Kernel version", "uname -r"],
    ["All uname fields", "uname -a"],
    ["Runtime kernel params", "sysctl -a"],
    ["Persist sysctl", "/etc/sysctl.d/*.conf"],
    ["Increase file handles example", "fs.file-max"],
    ["swappiness", "vm.swappiness (0-100)"],
    ["dmesg timestamp", "dmesg -T"],
    ["kdump service purpose", "capture vmcore on panic"],
  ]),
];
